---
- name: Configurar Servidor de Banco de Dados
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml  
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devops"
  tasks:
    - name: Configurar os hosts do lab Ansible
      lineinfile: line "{{item}}" path=/etc/hosts
      with_items:
        - 192.168.0.2 control-node
        - 192.168.0.3 app01
        - 192.168.0.4 db01
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql
      become: yes